import { Animal } from "@/components/AnimalCard";

export const animals: Animal[] = [
  {
    id: 1,
    name: "Max",
    species: "dog",
    breed: "Labrador mix",
    age: "2 ani",
    gender: "M",
    location: "București, Sector 3",
    vaccinated: true,
    sterilized: false,
    image: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=500&q=80",
    description: "Max este un câine jucăuș și prietenos, găsit abandonat în parcul Tineretului. Se înțelege bine cu oamenii și iubește plimbările lungi.",
    status: "available",
    postedBy: "Ioana M.",
    postedAt: "2026-04-15",
  },
  {
    id: 2,
    name: "Luna",
    species: "cat",
    breed: "Europeană comună",
    age: "1 an",
    gender: "F",
    location: "Cluj-Napoca",
    vaccinated: true,
    sterilized: true,
    image: "https://images.unsplash.com/photo-1574158622682-e40e69881006?w=500&q=80",
    description: "Luna este o pisicuță blândă și afectuoasă, gasită în stradă. Îi place să toarcă și să se gudure. Se potrivește perfect într-un apartament.",
    status: "available",
    postedBy: "Andrei P.",
    postedAt: "2026-04-16",
  },
  {
    id: 3,
    name: "Rocky",
    species: "dog",
    breed: "German Shepherd mix",
    age: "3 ani",
    gender: "M",
    location: "Timișoara",
    vaccinated: true,
    sterilized: true,
    image: "https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=500&q=80",
    description: "Rocky este un câine loial și inteligent. A fost găsit pe câmp fără stăpân. Este foarte bun cu copiii și adoră joaca.",
    status: "pending",
    postedBy: "Maria C.",
    postedAt: "2026-04-10",
  },
  {
    id: 4,
    name: "Mimi",
    species: "cat",
    breed: "Persană mix",
    age: "6 luni",
    gender: "F",
    location: "Iași",
    vaccinated: false,
    sterilized: false,
    image: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=500&q=80",
    description: "Mimi este un pui de pisică găsit singur. Are nevoie de vaccinare și multă dragoste. Foarte curioasă și energică.",
    status: "available",
    postedBy: "Elena D.",
    postedAt: "2026-04-17",
  },
  {
    id: 5,
    name: "Bruno",
    species: "dog",
    breed: "Rottweiler mix",
    age: "4 ani",
    gender: "M",
    location: "Brașov",
    vaccinated: true,
    sterilized: false,
    image: "https://images.unsplash.com/photo-1568572933382-74d440ac117f?w=500&q=80",
    description: "Bruno are un aspect impunător dar un suflet de aur. Extrem de blând și ascultător. Caută o familie cu curte.",
    status: "available",
    postedBy: "Mihai T.",
    postedAt: "2026-04-14",
  },
  {
    id: 6,
    name: "Cleo",
    species: "cat",
    breed: "Siam mix",
    age: "2 ani",
    gender: "F",
    location: "Constanța",
    vaccinated: true,
    sterilized: true,
    image: "https://images.unsplash.com/photo-1561948955-570b270e7c36?w=500&q=80",
    description: "Cleo este vocală și inteligentă, tipic pentru rasele orientale. Adoră atenția și se plictisește singură. Perfectă pentru un stăpân activ.",
    status: "available",
    postedBy: "Ana R.",
    postedAt: "2026-04-13",
  },
];
